baseURL = 'https://–ö–∏–±–µ—Ä–ø–æ–ª–∏–≥–æ–Ω.—Ä—Ñ/'
languageCode = 'ru-ru'
title = '–ö–∏–±–µ—Ä–ø–æ–ª–∏–≥–æ–Ω'
theme = "ananke"

[params]
  description = "–ö–∏–±–µ—Ä–ø–æ–ª–∏–≥–æ–Ω - —ç—Ç–æ –º–µ—Å—Ç–æ –¥–ª—è –æ–±—É—á–µ–Ω–∏—è –∏ —Ç—Ä–µ–Ω–∏—Ä–æ–≤–∫–∏ —Å–ø–µ—Ü–∏–∞–ª–∏—Å—Ç–æ–≤ –ø–æ –∫–∏–±–µ—Ä-–±–µ–∑–æ–ø–∞—Å–Ω–æ—Å—Ç–∏."
  author = "–°—Ç–∞–ª—å–º–∞—Ö–æ–≤ –ò–≤–∞–Ω –°–µ—Ä–≥–µ–µ–≤–∏—á, 241-3211"
  themeColor = "#2c3e50" 

[menu]
  [[menu.main]]
    name = "–ì–ª–∞–≤–Ω–∞—èüìå"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "–û –ø—Ä–æ–µ–∫—Ç–µ‚ÑπÔ∏è"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "–£—á–∞—Å—Ç–Ω–∏–∫–∏ü§ù"
    url = "/team/"
    weight = 3
  [[menu.main]]
    name = "–ñ—É—Ä–Ω–∞–ªüì∞"
    url = "/blog/"
    weight = 4
  [[menu.main]]
    name = "–†–µ—Å—É—Ä—Å—ãüåê"
    url = "/resources/"
    weight = 5

